### PR TITLE
A canonical way to create ExtractedLicenseInfo (Helper method and documentation, Issue #215)

### LINKED ISSUE #215: In need of a canonical way to add license texts for licenseRefs / Maybe bugged?
Trying to implement a custom "exporter" that converts a detailed, custom SBOM format to SPDX, I encountered some _really weird behaviour_ regarding the implementation of Chapter 10 "Other licensing information detected section", which I believe corresponds to the `ExtractedLicenseInfo` class in the library.
Since the base SPDX license list is insufficient for our use, we use both licenses from the list and licenseRefs to maintain correctness and detail in all our license expressions.

Using the library, I noticed that after converting and adding artifacts/software components as SPDX packages (maybe also files at some point), the converter programmatically finds and adds license texts for each custom licenseRef.
However, I couldn't find an example or documentation about how this is supposed to be done.

And that is the main question: _**What's the supported / recommended way to add custom license texts**_ to a document with the java library?

Trying to figure this out myself, I encountered some counterintuitive behaviour that may be caused by bugs in the implementation:

In our use-case, we want to write the resulting SPDX document to JSON using the `spdx-java-jackson-store` with `MultiFormatStore`.
I think it has to do with a combination of the store's behaviour, `ModelSet#add` and the use of `ExtractedLicenseInfo#id` to hold the licenseRef.
I think that when I try to add my `new ExtractedLicenseInfo` later, with the correct licenseRef in the id field, the store will reject this new, completed object, instead keeping a previously added `AnyLicenseInfo` unchanged, which didn't have the text yet.

As a user, these unique ids and the order in which I add license expressions and corresponding license texts are an implementation detail that I do not want to worry about.

---

Again, since I don't know the correct way, i experimented, but any interface I could find was unsatisfactory. To demonstrate my issues with current behaviour, I attached a class containing examples on some issues I am trying to demonstrate.
In the code, `// PROBLEM:` comments try to highlight what I feel the issue is.

Regrettably, the code ended up being messy. As a summary for each example:

#### Example 1

Simply using `document.addExtractedLicenseInfos(new ExtractedLicenseInfo(licenseRef, text))` doesn't make the correct `text` show up in the JSON.

- I think this is the way _it should work_, since info in this section would be somewhat independent of what licenseRefs have previously been added through other packages.

#### Example 2

Since [Example 1](#example-1) doesn't work, I tried to use an instance returned by `parseSPDXLicenseString`.

- this did not work, as the issue wasn't with the construction of `ExtractedLicenseInfo` but with the way objects are resolved.
- this makes for bad code, since we have to speculate on the real type of the given `AnyLicenseInfo` (and cast to `ExtractedLicenseInfo` to be able to call `SpdxDocument#addExtractedLicenseInfos`)

Through extensive browsing of source code, I later found out about `LicenseInfoFactory.parseSPDXLicenseString`'s overloading, leading to [Example 4](#example-4).

#### Example 3

This demonstrates a hack that immediately adds a license text just after first parsing the expression that contains it.

- demonstrates that an instance of `ExtractedLicenseInfo` is remembered in some obscure part of the store without explicitly adding it (unsure where from, probably somewhere under `SpdxDocument#createPackage`?)
  - later the instance is found present already by matching its `id`, breaking `hasExtractedLicensingInfos` when manually adding `ExtractedLicenseInfo`
- this solution is unintuitive and makes for hacky code
- unsuitable to my use case for technical reasons
  - I need to be able to add license texts in a _later processing stage_.

#### Example 4

This is similar to [Example 2](#example-2), abusing `LicenseInfoFactory#parseSPDXLicenseString`. It will return a writable instance to which I add the text inplace.

- same disadvantages as [Example 2](#example-2), except it produces the desired result (text shows up in `hasExtractedLicensingInfos`)
- bad api, this terrible hack leads to bad code and bad stability (since the interface is buried in implementation details).
- it's the way I bodged it... because I found no other way to make my program work
- demonstrates that `addExtractedLicenseInfos` **doesn't add the given object** to `hasExtractedLicensingInfos` **at all**!
  Instead, it later resolves something by "id" in some non-trivial way, depending on what licenseRefs are / were found in previously present license expressions.

I think a user of the library:

- shouldn't have to call `parseSPDXLicenseString` with its store, etc as parameters like i did here
- shouldn't ever have to rely on `parseSPDXLicenseString` giving the exact same instance between calls to achieve functionality
- should instead be able to add and remove information as objects freely
  - without them having unexpected side-effects (like an earlier package addition leading to broken license texts in `hasExtractedLicensingInfos`)

---

To conclude, I believe a change in the library's behaviour is required.
Example 1 could be a first step towards a better implementation.

So: If needed, I'll try to debug further for a PR once I know the way things _should_ work.

### PR DESCRIPTION
**Pull request by jkrae-metaeffekt**
Adds a helper class in ModelObject for correct creation of ExtractedLicenseInfo objects. This should resolve #215.

I also added documentation and comments regarding correct use of such objects. These may need correction:

It appeared to me that instances `ExtractedLicenseInfo` and an `SpdxDocument` become inherently linked after construction and are only assumed to produce correct behaviour when used together. I tried to document this, since it's a detail critical to data integrity but remains intransparent to me due to the complex workings of \*ModelStore.:
https://github.com/jkrae-metaeffekt/Spdx-Java-Library/blob/fbfd9acdc9aa81a2f17c7e5dff101c1fec495412/src/main/java/org/spdx/library/model/ModelObject.java#L1420C2-L1422 .

Please correct me on this. In case of correction, the other added javadocs may need adjustment, too.

edit: formatting fix

### CODE REVIEW

File: src/main/java/org/spdx/library/model/ModelObject.java [hunk 1]
```diff
@@ -40,13 +40,8 @@
 import org.spdx.library.model.enumerations.ReferenceCategory;
 import org.spdx.library.model.enumerations.RelationshipType;
 import org.spdx.library.model.enumerations.SpdxEnumFactory;
-import org.spdx.library.model.license.AnyLicenseInfo;
-import org.spdx.library.model.license.ConjunctiveLicenseSet;
+import org.spdx.library.model.license.*;
```
Comment (pmonks) [inline src/main/java/org/spdx/library/model/ModelObject.java:43]: Based on the existing codebase, I _think_ @goneall prefers explicit imports, rather than wildcard imports.  FWIW I'd be in favour of using wildcard imports though, if he's open to that.

**Review by pmonks — APPROVED** [review]
Other than my trivial comment about imports, this looks great!  I'll give @goneall a chance to weigh in too, though I know he's OOO for a few weeks.

What kind of timeline are you hoping to have this change integrated in, @jkrae-metaeffekt?  Note that while I (think) I can merge this PR, I don't have the means to cut a new release (and even if I did, I'd want @goneall to approve that first).

File: src/main/java/org/spdx/library/model/ModelObject.java (hunk 1 above)
Comment (jkrae-metaeffekt) [reply src/main/java/org/spdx/library/model/ModelObject.java:43]: Fair point about keeping style with the imports. Do you reckon I should just change history and force-push this fix?

**Comment by jkrae-metaeffekt** [comment]
Timeline? Huh. "ASAP" is just about the most useless comment to that question, i guess.

I'm now using the correct constructor as a workaround for now (see #216). So my code works now.
It would undoubtedly be nice to have in the next release, though.

File: src/main/java/org/spdx/library/model/ModelObject.java (hunk 1 above)
Comment (goneall) [reply src/main/java/org/spdx/library/model/ModelObject.java:43]: I'm OK with the wildcards and the minor style inconsistency in using a mix of specific imports and wildcard.  I have my IDE set to generate the specific imports - mainly to avoid possible conflicts but in this case the public classes shouldn't create any conflicts.

**Review by goneall — APPROVED** [review]
Thanks @jkrae-metaeffekt - changes look good.
