### PR TITLE
Handle InvalidLicenseExpression types converting from SPDX 2 to 3

### LINKED ISSUE #406: SPDX Conversion from SPDX 2.X to SPDX 3.X fails if there is an InvalidLicenseExpression
This is due to unimplemented conversions for the recently added types.

### PR DESCRIPTION
**Pull request by goneall**
Fixes #406

### CODE REVIEW

File: src/main/java/org/spdx/library/conversion/Spdx2to3Converter.java [hunk 1]
```diff
@@ -844,6 +845,33 @@ public OrLaterOperator convertAndStore(org.spdx.library.model.v2.license.OrLater
...
 		return toOrLaterOperator;
 	}
+
+	/**
+	 * Converts an SPDX spec version 2 SPDX InvalidLicenseExpression to an SPDX spec version 3 SPDX InvalidLicenseExpression and store the result
+	 * @param fromInvalidExpression an SPDX spec version 2 InvalidLicenseExpression
+	 * @return an SPDX spec version 3 InvalidLicenseExpression
+	 * @throws InvalidSPDXAnalysisException on any errors converting
+	 */
+	public InvalidLicenseExpression convertAndStore(org.spdx.library.model.v2.license.InvalidLicenseExpression fromInvalidExpression) throws InvalidSPDXAnalysisException {
```
Comment (bact) [inline src/main/java/org/spdx/library/conversion/Spdx2to3Converter.java]:
```suggestion
	public InvalidLicenseExpression convertAndStore(org.spdx.library.model.v2.license.InvalidLicenseExpression fromInvalidLicenseExpression) throws InvalidSPDXAnalysisException {
```

Since this is a public API, should we keep the full name here?

(I see an example from ExtractedLicenseInfo -> fromExtractedLicenseInfo at line 802)

File: src/main/java/org/spdx/library/conversion/Spdx2to3Converter.java [hunk 2]
```diff
@@ -844,6 +845,33 @@ public OrLaterOperator convertAndStore(org.spdx.library.model.v2.license.OrLater
...
+		if (Objects.nonNull(existingUri)) {
+			// small window if conversion occurred since the last check already converted
+			return (InvalidLicenseExpression)getExistingObject(fromInvalidExpression.getObjectUri(),
+					"SimpleLicensing.InvalidLicenseExpression").get();
+		}
+		InvalidLicenseExpression toInvalidLicExpression = (InvalidLicenseExpression)SpdxModelClassFactoryV3.getModelObject(toModelStore,
+				toObjectUri, "SimpleLicensing.InvalidLicenseExpression", copyManager, true, defaultUriPrefix);
+		toInvalidLicExpression.setCreationInfo(defaultCreationInfo);
+		toInvalidLicExpression.setMessage(fromInvalidExpression.getMessage());
+		toInvalidLicExpression.setLicenseExpression(fromInvalidExpression.getMessage());
```
Comment (bact) [inline src/main/java/org/spdx/library/conversion/Spdx2to3Converter.java]: Not sure about why we put the message from the SPDX v2 InvalidExpression.getMessage() to the SPDX v3 LicenseExpression.

Please ignore if this is intentional.

File: src/main/java/org/spdx/library/conversion/Spdx2to3Converter.java (hunk 1 above)
Comment (goneall) [reply src/main/java/org/spdx/library/conversion/Spdx2to3Converter.java]: Good point - I'll update the parameter name

File: src/main/java/org/spdx/library/conversion/Spdx2to3Converter.java (hunk 2 above)
Comment (goneall) [reply src/main/java/org/spdx/library/conversion/Spdx2to3Converter.java]: This is intentional - we're just copying the properties over from the SPDX Version 2 instance

**Review by bact — APPROVED** [review]
